Added page for editing role permissions
TritonSE/TSE-Oktavian pull request #47
Opened 2021-05-10 08:27 UTC by Benson272

### Administrative Info
Monday Board ID: 1181559666
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
Added a page to edit roles

### Testing
How did you confirm your changes worked? 
1) Went to the page to display all roles
2) clicked on the edit button for a role
3) checked to make sure default permissions were correct
4) checked to make sure checkboxes work
(Functionality for deleting and updated not implemented in backend yet )

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Default view when opening Developer permissions
![image](https://user-images.githubusercontent.com/55808666/117629002-9452d300-b12e-11eb-9cc8-23c6e089687f.png)

Default view when opening President permissions
![image](https://user-images.githubusercontent.com/55808666/117629193-c401db00-b12e-11eb-8fb3-0e8cb3710de7.png)

Changing permissions of role (currently doesn't do anything to backend)
![image](https://user-images.githubusercontent.com/55808666/117629328-e693f400-b12e-11eb-8376-e66335cabd84.png)

2021-05-10 09:26 UTC, AnsonLee99 requested changes
There is one more button handle for the "Create new role" button where EditRoles should be hooked up.
https://github.com/TritonSE/TSE-Oktavian/blob/d3c75bcdb28652aa61f1c6228f6df4b26559f457/frontend/src/pages/admin/roles/Roles.js#L77

2021-05-10 09:37 UTC, AnsonLee99 commented
Also, would we want to wait on this PR until Justin finishes his edit role backend routes?

2021-05-10 19:04 UTC, hahsu requested changes

2021-05-10 19:04 UTC, hahsu commented on frontend/src/components/RolePermissionsCard.js
> +          Save Changes
This button needs to say Save Changes or Create depending on if we came from editing or creating

2021-05-18 05:01 UTC, hahsu requested changes

2021-05-18 05:01 UTC, hahsu commented on frontend/src/components/RolePermissionsCard.js
> +    }
I'm a bit confused by this, why are we checking for `!=== null?` I assumed that event.target.checked would always be true or false. Also how do you know that permissions[field_name] is an indented field? Don't we only want to only make `permissions["admin"] = false ` if an indented box was unchecked?

2021-05-18 06:59 UTC, AnsonLee99 approved these changes
lgtm!

2021-05-19 03:00 UTC, hahsu approved these changes
lgtm, thanks!

2021-05-19 08:30 UTC, merged

2021-05-19 14:56 UTC, justinyaodu approved these changes
Suggested one tiny change, LGTM!