Refactor/justinyaodu/1290059430 replace admin permission
TritonSE/TSE-Oktavian pull request #52
Opened 2021-05-16 20:58 UTC by justinyaodu

### Administrative Info
Monday Board ID: 1181559666
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
* Renamed the `admin` permission to `user_edit`
* Changed each occurrence of `admin` in the codebase to `user_edit` or `role_management`, as appropriate
* Added test scripts for user edit and role edit routes

### Testing
How did you confirm your changes worked? 
* Logged in as the example president and confirmed that the role settings sidebar option showed up, and that the edit menu showed up on a user's profile
* Logged in as the example developer and confirmed that the above UI elements did not show up
* Ran the role edit test script to confirm that role editing still works
* Ran the user edit test script to confirm that user editing still works

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Logged in as President |
| --- |
| ![screenshot-20210516-135442](https://user-images.githubusercontent.com/19500553/118412393-80d3ca80-b64e-11eb-9df2-d7f26a687ed2.png) |

| Logged in as Developer |
| --- |
| ![screenshot-20210516-135453](https://user-images.githubusercontent.com/19500553/118412402-90ebaa00-b64e-11eb-923f-06ee7ec7bc19.png) |

2021-05-16 22:20 UTC, hahsu requested changes
Can we update the PM permissions in mock.js: 
https://github.com/TritonSE/TSE-Oktavian/blob/46d0bb9702fb3b35b75ca56df8816fdab55f5bd4/backend/services/mock.js#L34
PM's should have edit_project permissions.

2021-05-16 22:20 UTC, hahsu commented on backend/services/mock.js
>      permissions: {
Can we update these permissions as well, President should have all of the permissions

2021-05-16 23:51 UTC, justinyaodu commented
Thanks for the feedback! Let me know if you notice anything else :slightly_smiling_face:

2021-05-17 02:56 UTC, hahsu approved these changes
lgtm, thank you!

2021-05-18 00:58 UTC, AnsonLee99 approved these changes
LGTM!

2021-05-18 02:17 UTC, merged