User deactivation feature
TritonSE/TSE-Oktavian pull request #53
Opened 2021-05-17 08:22 UTC by lynguyxn

### Administrative Info
Monday Board ID: 1181559666
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added confirm deactivation popup on frontend when user clicks "Deactivate"
- Created backend delete user route and linked it to the frontend for the deactivate button
- Redirect user to Roster page after deactivating another account or Login page after deactivating their own account
- Users with either roster edit or account activation permissions can see settings icon
- Users with roster edit permissions (currently "admin" permissions before Justin's PR) but not deactivate permissions receives a "You do not have the necessary permissions" error message when "Deactivate" button is clicked

### Testing
How did you confirm your changes worked? 
- Logged in as president, deleted developer account, and checked if the developer account is deleted from database
- Logged in as user with no delete permission, clicked on deactivate button, and checked it gave a permissions error

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Deactivation Pop-up |
| --- |
| ![1](https://user-images.githubusercontent.com/64985802/118454435-37ff2e80-b6ad-11eb-8c24-9844109ede57.PNG) |

| President View - Redirect to Roster after deleting Developer account |
| --- |
| ![2](https://user-images.githubusercontent.com/64985802/118454545-56652a00-b6ad-11eb-8c90-d74e52e89eb3.PNG) |

| Database deletion of Developer account |
| --- |
| ![3](https://user-images.githubusercontent.com/64985802/118454614-6bda5400-b6ad-11eb-908e-747f8a4fe0b5.PNG) |

| No deactivate but has roster edit permissions view |
| --- |
| ![4](https://user-images.githubusercontent.com/64985802/118454688-7f85ba80-b6ad-11eb-9adc-49b3138c8863.PNG) |

| Redirect to Login after deleting their own account |
| --- |
| ![image](https://user-images.githubusercontent.com/64985802/118455265-e0ad8e00-b6ad-11eb-9883-1820599a7fbf.png) |

2021-05-17 13:39 UTC, justinyaodu requested changes
When a user has edit permissions but not deactivate permissions, can we show only the edit option in the menu? I feel like that might be less confusing. Other than that, LGTM!

2021-05-17 18:29 UTC, hahsu reviewed
I'll look at this after Justin's PR is merged into main

2021-05-17 18:42 UTC, lynguyxn commented
> When a user has edit permissions but not deactivate permissions, can we show only the edit option in the menu? I feel like that might be less confusing than the popup. Other than that, LGTM!

Good idea, made the changes :)

2021-05-17 19:30 UTC, justinyaodu approved these changes
LGTM!

2021-05-19 03:02 UTC, hahsu approved these changes
lgtm other than the one comment!

2021-05-19 03:02 UTC, hahsu commented on backend/services/users.js
> +async function deleteUser(_id) {
Can you add a header comment like the rest of the functions have in this file?

2021-05-19 05:57 UTC, merged