Add graduation info to register page
TritonSE/TSE-Oktavian pull request #57
Opened 2021-05-23 00:42 UTC by lynguyxn

### Administrative Info
Monday Board ID: 1181559666
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added graduation quarter dropdown and graduation year text field on Register page (set default grad quarter to be Spring since it's most common)
- Added backend validation check for required graduation quarter and year fields in Register route
- Removed default grad year when registering (used before because we didn't have an input for entering required grad year field on Register page)

### Testing
How did you confirm your changes worked? 
- Created a new user by using the Register page and checked to see if fields are populated correctly in database

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Register Page |
| --- |
| ![image](https://user-images.githubusercontent.com/64985802/119244246-4ae98700-bb23-11eb-9189-3bb3b516d9a6.png) |

| Graduation Quarter Dropdown |
| --- |
| ![image](https://user-images.githubusercontent.com/64985802/119244076-90a55000-bb21-11eb-8125-2b451e988147.png) |

| Required Field Checks |
| --- |
| ![image](https://user-images.githubusercontent.com/64985802/119244088-bd596780-bb21-11eb-888d-c82ea705616f.png) |

| Valid Year Check |
| --- |
| ![image](https://user-images.githubusercontent.com/64985802/119244334-6acd7a80-bb24-11eb-9e89-3cb9394a10b9.png) |

| New User in Database After Register |
| --- |
| ![image](https://user-images.githubusercontent.com/64985802/119244310-2e018380-bb24-11eb-9588-28822e196e30.png) |

2021-05-23 09:42 UTC, Benson272 requested changes

2021-05-23 22:08 UTC, lynguyxn commented on frontend/src/pages/Register.js
> +                type="text"
oops yeah I missed that
thanks for catching it!

2021-05-24 06:48 UTC, Benson272 approved these changes
LGTM

2021-05-24 22:29 UTC, hahsu approved these changes
lgtm, thanks!

2021-05-24 22:30 UTC, merged